drop database BMS_DB;
create database BMS_DB;
use BMS_db;
create table CUSTOMER_PERSONAL_INFO
( CUSTOMER_ID VARCHAR(5), CUSTOMER_NAME VARCHAR(30),
DATE_OF_BIRTH DATE, GUARDIAN_NAME VARCHAR(30),
ADDRESS VARCHAR(50), CONTACT_NO BIGINT(10), MAIL_ID VARCHAR(30),
GENDER CHAR(1), MARITAL_STATUS VARCHAR(10), IDENTIFICATION_DOC_TYPE VARCHAR(20),
ID_DOC_NO VARCHAR(20), CITIZENSHIP VARCHAR(10), 
CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID) );
SHOW TABLES;

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
CUSTOMER_ID VARCHAR(5), REFERENCE_ACC_NAME VARCHAR(20),
REFERENCE_ACC_NO BIGINT(16), REFERENCE_ACC_ADDRESS VARCHAR(50),
RELATION varchar(25),
 CONSTRAINT  CUST_REF_INFO_PK PRIMARY KEY(CUSTOMER_ID),
 CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID)
);
SHOW TABLES;

CREATE TABLE BANK_INFO (
IFSC_CODE VARCHAR(15),
BANK_NAME VARCHAR(25),
BRANCH_NAME VARCHAR(25),
CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);
SHOW TABLES;
 
CREATE TABLE ACCOUNT_INFO (
ACCOUNT_NO BIGINT(16),
CUSTOMER_ID VARCHAR(5),
ACCOUNT_TYPE VARCHAR(10),
REGISTRATION_DATE DATE,
ACTIVATION_DATE DATE,
IFSC_CODE VARCHAR(10),
INTREST DECIMAL(7,2),
INITIAL_DEPOSIT BIGINT(10),
CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO(CUSTOMER_ID),
CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO(IFSC_CODE)
);
SHOW TABLES;
INSERT INTO BANK_INFO (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('HDVL0012','HDFC','DURGAPUR');
INSERT INTO BANK_INFO (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('SBITN0123','SBI','TNAGAR');
INSERT INTO BANK_INFO (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('ICITN0232','ICICI','TNAGAR');
INSERT INTO BANK_INFO (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('ICIPG0242','ICICI','PERUNGUDI');
INSERT INTO BANK_INFO (IFSC_CODE, BANK_NAME, BRANCH_NAME) VALUES('SBISD0113','SBI','SAIDAPET');
SELECT * FROM BANK_INFO;

INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID , CUSTOMER_NAME,
DATE_OF_BIRTH , GUARDIAN_NAME, ADDRESS , CONTACT_NO , MAIL_ID,
GENDER , MARITAL_STATUS , IDENTIFICATION_DOC_TYPE ,
ID_DOC_NO , CITIZENSHIP  ) VALUES('1','RAMAN SINGH','23.11.2020','SHARAM SINGH', '451 TILAK STREET RAMNAGAR UP',
'8004836665','RAMAN@123GMAIL.COM', 'M', 'MARRIED','AADHAR CARD','452122416732', 'INDIAN');
UPDATE CUSTOMER_PERSONAL_INFO SET DATE_OF_BIRTH= '1981.11.11' WHERE CUSTOMER_ID= '1';

SELECT * FROM CUSTOMER_PERSONAL_INFO;
INSERT INTO CUSTOMER_PERSONAL_INFO (CUSTOMER_ID , CUSTOMER_NAME,
DATE_OF_BIRTH , GUARDIAN_NAME, ADDRESS , CONTACT_NO , MAIL_ID,
GENDER , MARITAL_STATUS , IDENTIFICATION_DOC_TYPE ,
ID_DOC_NO , CITIZENSHIP  ) VALUES('2','GULSHAN KAPOOR','23.11.2020','GROVER SINGH', 'P761 TILAK STREET RAMNAGAR UP',
'9334836665','GULSHAN@123GMAIL.COM', 'M', 'MARRIED','AADHAR CARD','452122999988', 'INDIAN');

SELECT* FROM CUSTOMER_PERSONAL_INFO;
UPDATE CUSTOMER_PERSONAL_INFO SET DATE_OF_BIRTH= '1983.08.06' WHERE CUSTOMER_ID= '2';
USE BMS_DB;





